In [1]:
import pandas as pd

## Reading Data

In [2]:
movies = pd.read_csv("data/IMDB_Top250movies2_OMDB_Detailed.csv")
movies = movies.drop(columns=["Unnamed: 0"])
movies

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,The Shawshank Redemption,1994,R,14 Oct 1994,142 min,"Crime, Drama",Frank Darabont,"Stephen King (short story ""Rita Hayworth and S...","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/shawshank_rede...,27 Jan 1998,NaN,Columbia Pictures,NaN,True
1,The Godfather,1972,R,24 Mar 1972,175 min,"Crime, Drama",Francis Ford Coppola,"Mario Puzo (screenplay), Francis Ford Coppola ...","Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather/,09 Oct 2001,NaN,Paramount Pictures,http://www.thegodfather.com,True
2,The Godfather: Part II,1974,R,20 Dec 1974,202 min,"Crime, Drama",Francis Ford Coppola,"Francis Ford Coppola (screenplay), Mario Puzo ...","Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather_part...,24 May 2005,NaN,Paramount Pictures,http://www.thegodfather.com/,True
3,The Dark Knight,2008,PG-13,18 Jul 2008,152 min,"Action, Crime, Drama",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knight/,09 Dec 2008,"$533,316,061",Warner Bros. Pictures/Legendary,http://thedarkknight.warnerbros.com/,True
4,12 Angry Men,1957,APPROVED,01 Apr 1957,96 min,"Crime, Drama",Sidney Lumet,"Reginald Rose (story), Reginald Rose (screenplay)","Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/1000013-12_ang...,06 Mar 2001,NaN,Criterion Collection,http://www.criterion.com/films/27871-12-angry-men,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Pirates of the Caribbean: The Curse of the Bla...,2003,PG-13,09 Jul 2003,143 min,"Action, Adventure, Fantasy",Gore Verbinski,"Ted Elliott (screen story), Terry Rossio (scre...","Johnny Depp, Geoffrey Rush, Orlando Bloom, Kei...",Blacksmith Will Turner teams up with eccentric...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/pirates_of_the...,02 Dec 2003,"$305,343,252",Buena Vista Pictures,http://disney.go.com/disneyvideos/liveaction/p...,True
246,What Ever Happened to Baby Jane?,1962,APPROVED,NaN,134 min,"Drama, Horror, Thriller",Robert Aldrich,"Henry Farrell (from the novel by), Lukas Helle...","Bette Davis, Joan Crawford, Victor Buono, Wesl...",A former child star torments her paraplegic si...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/what-ever-happ...,25 Sep 1997,NaN,Warner Bros. Pictures,NaN,True
247,"Paris, Texas",1984,R,19 Sep 1984,145 min,Drama,Wim Wenders,"L.M. Kit Carson (adaptation), Sam Shepard","Harry Dean Stanton, Sam Berry, Bernhard Wicki,...","Travis Henderson, an aimless drifter who has b...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/paris_texas/,14 Dec 2004,NaN,20th Century Fox,NaN,True
248,Drishyam,2015,NOT RATED,31 Jul 2015,163 min,"Crime, Drama, Mystery",Nishikant Kamat,"Jeethu Joseph (original story), Upendra Sidhay...","Ajay Devgn, Shriya Saran, Tabu, Rajat Kapoor",Desperate measures are taken by a man who trie...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/drishyam_2015/,NaN,NaN,B4U US,http://www.www.drishyamthefilm.com,True
249,PK,2014,NaN,19 Dec 2014,153 min,"Comedy, Drama, Fantasy",Rajkumar Hirani,"Rajkumar Hirani, Abhijat Joshi","Aamir Khan, Anushka Sharma, Sanjay Dutt, Boman...",A stranger in the city asks questions no one h...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/pk/,NaN,"$9,027,790",UTV Communications,http://pkmovie.in/,True

### See all columns

In [3]:
pd.set_option('display.max_columns', None)
movies.head()

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,Ratings.Source,Ratings.Value,Metascore,imdbRating,imdbVotes,imdbID,Type,tomatoMeter,tomatoImage,tomatoRating,tomatoReviews,tomatoFresh,tomatoRotten,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,The Shawshank Redemption,1994,R,14 Oct 1994,142 min,"Crime, Drama",Frank Darabont,"Stephen King (short story ""Rita Hayworth and S...","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,English,USA,Nominated for 7 Oscars. Another 19 wins & 30 n...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.3/10,80.0,9.3,"1,825,626",tt0111161,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/shawshank_rede...,27 Jan 1998,NaN,Columbia Pictures,NaN,True
1,The Godfather,1972,R,24 Mar 1972,175 min,"Crime, Drama",Francis Ford Coppola,"Mario Puzo (screenplay), Francis Ford Coppola ...","Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...,"English, Italian, Latin",USA,Won 3 Oscars. Another 23 wins & 27 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.2/10,100.0,9.2,"1,243,444",tt0068646,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather/,09 Oct 2001,NaN,Paramount Pictures,http://www.thegodfather.com,True
2,The Godfather: Part II,1974,R,20 Dec 1974,202 min,"Crime, Drama",Francis Ford Coppola,"Francis Ford Coppola (screenplay), Mario Puzo ...","Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...,"English, Italian, Spanish, Latin, Sicilian",USA,Won 6 Oscars. Another 10 wins & 20 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.0/10,85.0,9.0,"856,870",tt0071562,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather_part...,24 May 2005,NaN,Paramount Pictures,http://www.thegodfather.com/,True
3,The Dark Knight,2008,PG-13,18 Jul 2008,152 min,"Action, Crime, Drama",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...,"English, Mandarin","USA, UK",Won 2 Oscars. Another 151 wins & 153 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.0/10,82.0,9.0,"1,802,351",tt0468569,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knight/,09 Dec 2008,"$533,316,061",Warner Bros. Pictures/Legendary,http://thedarkknight.warnerbros.com/,True
4,12 Angry Men,1957,APPROVED,01 Apr 1957,96 min,"Crime, Drama",Sidney Lumet,"Reginald Rose (story), Reginald Rose (screenplay)","Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...,English,USA,Nominated for 3 Oscars. Another 16 wins & 8 no...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,8.9/10,96.0,8.9,"494,215",tt0050083,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/1000013-12_ang...,06 Mar 2001,NaN,Criterion Collection,http://www.criterion.com/films/27871-12-angry-men,True

In [4]:
pd.set_option('max_columns', None)
movies.head()

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Country,Awards,Poster,Ratings.Source,Ratings.Value,Metascore,imdbRating,imdbVotes,imdbID,Type,tomatoMeter,tomatoImage,tomatoRating,tomatoReviews,tomatoFresh,tomatoRotten,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,The Shawshank Redemption,1994,R,14 Oct 1994,142 min,"Crime, Drama",Frank Darabont,"Stephen King (short story ""Rita Hayworth and S...","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,English,USA,Nominated for 7 Oscars. Another 19 wins & 30 n...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.3/10,80.0,9.3,"1,825,626",tt0111161,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/shawshank_rede...,27 Jan 1998,NaN,Columbia Pictures,NaN,True
1,The Godfather,1972,R,24 Mar 1972,175 min,"Crime, Drama",Francis Ford Coppola,"Mario Puzo (screenplay), Francis Ford Coppola ...","Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...,"English, Italian, Latin",USA,Won 3 Oscars. Another 23 wins & 27 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.2/10,100.0,9.2,"1,243,444",tt0068646,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather/,09 Oct 2001,NaN,Paramount Pictures,http://www.thegodfather.com,True
2,The Godfather: Part II,1974,R,20 Dec 1974,202 min,"Crime, Drama",Francis Ford Coppola,"Francis Ford Coppola (screenplay), Mario Puzo ...","Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...,"English, Italian, Spanish, Latin, Sicilian",USA,Won 6 Oscars. Another 10 wins & 20 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.0/10,85.0,9.0,"856,870",tt0071562,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather_part...,24 May 2005,NaN,Paramount Pictures,http://www.thegodfather.com/,True
3,The Dark Knight,2008,PG-13,18 Jul 2008,152 min,"Action, Crime, Drama",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...,"English, Mandarin","USA, UK",Won 2 Oscars. Another 151 wins & 153 nominations.,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,9.0/10,82.0,9.0,"1,802,351",tt0468569,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knight/,09 Dec 2008,"$533,316,061",Warner Bros. Pictures/Legendary,http://thedarkknight.warnerbros.com/,True
4,12 Angry Men,1957,APPROVED,01 Apr 1957,96 min,"Crime, Drama",Sidney Lumet,"Reginald Rose (story), Reginald Rose (screenplay)","Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...,English,USA,Nominated for 3 Oscars. Another 16 wins & 8 no...,https://images-na.ssl-images-amazon.com/images...,Internet Movie Database,8.9/10,96.0,8.9,"494,215",tt0050083,movie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/1000013-12_ang...,06 Mar 2001,NaN,Criterion Collection,http://www.criterion.com/films/27871-12-angry-men,True

In [5]:
pd.set_option('max_columns', 2)
movies.head()

                      Title  ...  Response
0  The Shawshank Redemption  ...      True
1             The Godfather  ...      True
2    The Godfather: Part II  ...      True
3           The Dark Knight  ...      True
4              12 Angry Men  ...      True

[5 rows x 37 columns]

In [6]:
pd.reset_option("max_columns")
movies.head()

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,The Shawshank Redemption,1994,R,14 Oct 1994,142 min,"Crime, Drama",Frank Darabont,"Stephen King (short story ""Rita Hayworth and S...","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/shawshank_rede...,27 Jan 1998,NaN,Columbia Pictures,NaN,True
1,The Godfather,1972,R,24 Mar 1972,175 min,"Crime, Drama",Francis Ford Coppola,"Mario Puzo (screenplay), Francis Ford Coppola ...","Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather/,09 Oct 2001,NaN,Paramount Pictures,http://www.thegodfather.com,True
2,The Godfather: Part II,1974,R,20 Dec 1974,202 min,"Crime, Drama",Francis Ford Coppola,"Francis Ford Coppola (screenplay), Mario Puzo ...","Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather_part...,24 May 2005,NaN,Paramount Pictures,http://www.thegodfather.com/,True
3,The Dark Knight,2008,PG-13,18 Jul 2008,152 min,"Action, Crime, Drama",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knight/,09 Dec 2008,"$533,316,061",Warner Bros. Pictures/Legendary,http://thedarkknight.warnerbros.com/,True
4,12 Angry Men,1957,APPROVED,01 Apr 1957,96 min,"Crime, Drama",Sidney Lumet,"Reginald Rose (story), Reginald Rose (screenplay)","Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...,...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/1000013-12_ang...,06 Mar 2001,NaN,Criterion Collection,http://www.criterion.com/films/27871-12-angry-men,True

### Column width

In [7]:
movies[["Title", "Plot"]].head()

                      Title                                               Plot
0  The Shawshank Redemption  Two imprisoned men bond over a number of years...
1             The Godfather  The aging patriarch of an organized crime dyna...
2    The Godfather: Part II  The early life and career of Vito Corleone in ...
3           The Dark Knight  When the menace known as the Joker emerges fro...
4              12 Angry Men  A jury holdout attempts to prevent a miscarria...

In [8]:
pd.set_option("display.max_colwidth", 100)
movies[["Title", "Plot"]].head()

,Title,Plot
0,The Shawshank Redemption,"Two imprisoned men bond over a number of years, finding solace and eventual redemption through a..."
1,The Godfather,The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to...
2,The Godfather: Part II,"The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael..."
3,The Dark Knight,"When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos o..."
4,12 Angry Men,A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsi...

In [9]:
pd.set_option("display.max_colwidth", None)

movies[["Title", "Plot"]].head()

,Title,Plot
0,The Shawshank Redemption,"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency."
1,The Godfather,The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.
2,The Godfather: Part II,"The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on the family crime syndicate."
3,The Dark Knight,"When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham, the Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice."
4,12 Angry Men,A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.

In [10]:
pd.set_option("display.max_colwidth", 10)

movies[["Title", "Plot"]].head()

       Title       Plot
0  The Sh...  Two im...
1  The Go...  The ag...
2  The Go...  The ea...
3  The Da...  When t...
4  12 Ang...  A jury...

In [11]:
pd.reset_option("display.max_colwidth")

## Rows

In [12]:
pd.set_option("max_columns", 2) #Showing only two columns

pd.set_option("max_rows", None)
movies

                                                 Title  ...  Response
0                             The Shawshank Redemption  ...      True
1                                        The Godfather  ...      True
2                               The Godfather: Part II  ...      True
3                                      The Dark Knight  ...      True
4                                         12 Angry Men  ...      True
5                                     Schindler's List  ...      True
6                                         Pulp Fiction  ...      True
7        The Lord of the Rings: The Return of the King  ...      True
8                       The Good, the Bad and the Ugly  ...      True
9                                           Fight Club  ...      True
10   The Lord of the Rings: The Fellowship of the Ring  ...      True
11                                        Forrest Gump  ...      True
12      Star Wars: Episode V - The Empire Strikes Back  ...      True
13                                           Inception  ...      True
14               The Lord of the Rings: The Two Towers  ...      True
15                     One Flew Over the Cuckoo's Nest  ...      True
16                                          Goodfellas  ...      True
17                                          The Matrix  ...      True
18                                       Seven Samurai  ...      True
19                  Star Wars: Episode IV - A New Hope  ...      True
20                                         City of God  ...      True
21                                               Se7en  ...      True
22                            The Silence of the Lambs  ...      True
23                               It's a Wonderful Life  ...      True
24                                   Life Is Beautiful  ...      True
25                                  The Usual Suspects  ...      True
26                              Léon: The Professional  ...      True
27                                 Saving Private Ryan  ...      True
28                                       Spirited Away  ...      True
29                        Once Upon a Time in the West  ...      True
30                                  American History X  ...      True
31                                        Interstellar  ...      True
32                                              Psycho  ...      True
33                                          Casablanca  ...      True
34                                         City Lights  ...      True
35                                      The Green Mile  ...      True
36                                    The Intouchables  ...      True
37                                        Modern Times  ...      True
38                             Raiders of the Lost Ark  ...      True
39                                         Rear Window  ...      True
40                                         The Pianist  ...      True
41                                        The Departed  ...      True
42                          Terminator 2: Judgment Day  ...      True
43                                  Back to the Future  ...      True
44                                            Whiplash  ...      True
45                                           Gladiator  ...      True
46                                             Memento  ...      True
47                                        The Prestige  ...      True
48                                       The Lion King  ...      True
49                                      Apocalypse Now  ...      True
50                                               Alien  ...      True
51                                    Sunset Boulevard  ...      True
52   Dr. Strangelove or: How I Learned to Stop Worr...  ...      True
53                                  The Great Dictator  ...      True
54                                     Cinema Paradiso  ...      True
55                                 The Lives of Others  ...      True
56                              Grave of the Fireflies  ...      True
57                                      Paths of Glory  ...      True
58                                    Django Unchained  ...      True
59                                         The Shining  ...      True
60                                              WALL·E  ...      True
61                                     American Beauty  ...      True
62                               The Dark Knight Rises  ...      True
63                                   Princess Mononoke  ...      True
64                                              Aliens  ...      True
65                                              Oldboy  ...      True
66                         Once Upon a Time in America  ...      True
67                         Witness for the Prosecution  ...      True
68                                            Das Boot  ...      True
69                                        Citizen Kane  ...      True
70                                              Dangal  ...      True
71                                  North by Northwest  ...      True
72                                             Vertigo  ...      True
73          Star Wars: Episode VI - Return of the Jedi  ...      True
74                                      Reservoir Dogs  ...      True
75                                          Braveheart  ...      True
76                                                   M  ...      True
77                                 Requiem for a Dream  ...      True
78                                              Amélie  ...      True
79                                 Like Stars on Earth  ...      True
80                                  A Clockwork Orange  ...      True
81                                  Lawrence of Arabia  ...      True
82                                         Taxi Driver  ...      True
83                                    Double Indemnity  ...      True
84               Eternal Sunshine of the Spotless Mind  ...      True
85                                             Amadeus  ...      True
86                               To Kill a Mockingbird  ...      True
87                                         Toy Story 3  ...      True
88                                   Full Metal Jacket  ...      True
89                               2001: A Space Odyssey  ...      True
90                                 Singin' in the Rain  ...      True
91                                           Your Name  ...      True
92                                           The Sting  ...      True
93                                           Toy Story  ...      True
94                                     Bicycle Thieves  ...      True
95                                             The Kid  ...      True
96                                Inglourious Basterds  ...      True
97                                            3 Idiots  ...      True
98                                              Snatch  ...      True
99                     Monty Python and the Holy Grail  ...      True
100                                  L.A. Confidential  ...      True
101                             For a Few Dollars More  ...      True
102                                           The Hunt  ...      True
103                                  Good Will Hunting  ...      True
104                                           Scarface  ...      True
105                               My Father and My Son  ...      True
106                                      The Apartment  ...      True
107                                           Rashomon  ...      True
108                                       A Separation  ...      True
109                                         Metropolis  ...      True
110                 Indiana Jones and the Last Crusade  ...      True
111                                      All About Eve  ...      True
112                                            Yojimbo  ...      True
113                                      Batman Begins  ...      True
114                                                 Up  ...      True
115                                   Some Like It Hot  ...      True
116                   The Treasure of the Sierra Madre  ...      True
117                                         Unforgiven  ...      True
118                                           Downfall  ...      True
119                                        Raging Bull  ...      True
120                                           Die Hard  ...      True
121                                      The Third Man  ...      True
122                                 Children of Heaven  ...      True
123                                               Heat  ...      True
124                                   The Great Escape  ...      True
125                                          Chinatown  ...      True
126                                              Ikiru  ...      True
127                                    Pan's Labyrinth  ...      True
128                                 My Neighbor Totoro  ...      True
129                                        Baby Driver  ...      True
130                                         Inside Out  ...      True
131                                                Ran  ...      True
132                                      The Gold Rush  ...      True
133                                  On the Waterfront  ...      True
134                           The Secret in Their Eyes  ...      True
135                                               Room  ...      True
136                       The Bridge on the River Kwai  ...      True
137                                       Blade Runner  ...      True
138                               Howl's Moving Castle  ...      True
139                                         La La Land  ...      True
140                                          Incendies  ...      True
141                              Judgment at Nuremberg  ...      True
142                                   The Seventh Seal  ...      True
143                Lock, Stock and Two Smoking Barrels  ...      True
144                       Mr. Smith Goes to Washington  ...      True
145                                             Casino  ...      True
146                                   A Beautiful Mind  ...      True
147                                              Logan  ...      True
148                                   The Elephant Man  ...      True
149                                      Andrei Rublev  ...      True
150                                  Wild Strawberries  ...      True
151                                     V for Vendetta  ...      True
152                                        The General  ...      True
153                            The Wolf of Wall Street  ...      True
154                                            Warrior  ...      True
155                                         The Bandit  ...      True
156                                      Trainspotting  ...      True
157                                            Sunrise  ...      True
158                                  Dial M for Murder  ...      True
159                                        Gran Torino  ...      True
160                                    The Deer Hunter  ...      True
161                                      Hacksaw Ridge  ...      True
162                                 Gone with the Wind  ...      True
163                                              Fargo  ...      True
164                                   The Big Lebowski  ...      True
165                                    The Sixth Sense  ...      True
166                                          The Thing  ...      True
167                                       Finding Nemo  ...      True
168                                        Tokyo Story  ...      True
169                             No Country for Old Men  ...      True
170                                    Rang De Basanti  ...      True
171                         The Passion of Joan of Arc  ...      True
172                                     Cool Hand Luke  ...      True
173                                            Rebecca  ...      True
174                                        A Wednesday  ...      True
175                                There Will Be Blood  ...      True
176                           How to Train Your Dragon  ...      True
177                                  Kill Bill: Vol. 1  ...      True
178                                       Come and See  ...      True
179                                       Mary and Max  ...      True
180                                          Gone Girl  ...      True
181                                      Into the Wild  ...      True
182                              It Happened One Night  ...      True
183                                     Shutter Island  ...      True
184                                      Life of Brian  ...      True
185                                            Platoon  ...      True
186                                         Wild Tales  ...      True
187                                       Hotel Rwanda  ...      True
188                                               Rush  ...      True
189                                  The Wages of Fear  ...      True
190                                            Network  ...      True
191                          In the Name of the Father  ...      True
192                                        Stand by Me  ...      True
193                                      The 400 Blows  ...      True
194                                            Ben-Hur  ...      True
195                           The Grand Budapest Hotel  ...      True
196                                          Spotlight  ...      True
197                                 Mad Max: Fury Road  ...      True
198                                   12 Years a Slave  ...      True
199                                            Persona  ...      True
200                                Million Dollar Baby  ...      True
201                 Butch Cassidy and the Sundance Kid  ...      True
202                                      Jurassic Park  ...      True
203                                 Memories of Murder  ...      True
204                                      Amores Perros  ...      True
205                                 The Maltese Falcon  ...      True
206                                Munna Bhai M.B.B.S.  ...      True
207                                            Stalker  ...      True
208                                    The Truman Show  ...      True
209                              The Nights of Cabiria  ...      True
210                                 The Princess Bride  ...      True
211                                Hachi: A Dog's Tale  ...      True
212                 Nausicaä of the Valley of the Wind  ...      True
213                                     Before Sunrise  ...      True
214                       Star Wars: The Force Awakens  ...      True
215                                             Sholay  ...      True
216                                The Grapes of Wrath  ...      True
217       Harry Potter and the Deathly Hallows: Part 2  ...      True
218                                              Rocky  ...      True
219                                          Prisoners  ...      True
220                                      Touch of Evil  ...      True
221                                             Gandhi  ...      True
222                                         Diabolique  ...      True
223                                         Annie Hall  ...      True
224                                Catch Me If You Can  ...      True
225                                       Donnie Darko  ...      True
226                                     Monsters, Inc.  ...      True
227                                         Hera Pheri  ...      True
228                               The Bourne Ultimatum  ...      True
229                                     The Terminator  ...      True
230                                                 8½  ...      True
231                                   The Wizard of Oz  ...      True
232                                       Barry Lyndon  ...      True
233                                      Groundhog Day  ...      True
234                                           La Haine  ...      True
235                                     Twelve Monkeys  ...      True
236                                               Jaws  ...      True
237                                   Infernal Affairs  ...      True
238                        The Best Years of Our Lives  ...      True
239                                 Gangs of Wasseypur  ...      True
240                                           The Help  ...      True
241                               Beauty and the Beast  ...      True
242                                  Dog Day Afternoon  ...      True
243                              The Battle of Algiers  ...      True
244                               In the Mood for Love  ...      True
245  Pirates of the Caribbean: The Curse of the Bla...  ...      True
246                   What Ever Happened to Baby Jane?  ...      True
247                                       Paris, Texas  ...      True
248                                           Drishyam  ...      True
249                                                 PK  ...      True

[250 rows x 37 columns]

In [13]:
pd.reset_option("display.max_rows", None)

print("Default max_rows: {} and min_rows: {}".format(pd.get_option("display.max_rows"), pd.get_option("display.min_rows")))

movies

Default max_rows: 60 and min_rows: 10

                                                 Title  ...  Response
0                             The Shawshank Redemption  ...      True
1                                        The Godfather  ...      True
2                               The Godfather: Part II  ...      True
3                                      The Dark Knight  ...      True
4                                         12 Angry Men  ...      True
..                                                 ...  ...       ...
245  Pirates of the Caribbean: The Curse of the Bla...  ...      True
246                   What Ever Happened to Baby Jane?  ...      True
247                                       Paris, Texas  ...      True
248                                           Drishyam  ...      True
249                                                 PK  ...      True

[250 rows x 37 columns]

In [14]:
movies.head(20)

                                                Title  ...  Response
0                            The Shawshank Redemption  ...      True
1                                       The Godfather  ...      True
2                              The Godfather: Part II  ...      True
3                                     The Dark Knight  ...      True
4                                        12 Angry Men  ...      True
5                                    Schindler's List  ...      True
6                                        Pulp Fiction  ...      True
7       The Lord of the Rings: The Return of the King  ...      True
8                      The Good, the Bad and the Ugly  ...      True
9                                          Fight Club  ...      True
10  The Lord of the Rings: The Fellowship of the Ring  ...      True
11                                       Forrest Gump  ...      True
12     Star Wars: Episode V - The Empire Strikes Back  ...      True
13                                          Inception  ...      True
14              The Lord of the Rings: The Two Towers  ...      True
15                    One Flew Over the Cuckoo's Nest  ...      True
16                                         Goodfellas  ...      True
17                                         The Matrix  ...      True
18                                      Seven Samurai  ...      True
19                 Star Wars: Episode IV - A New Hope  ...      True

[20 rows x 37 columns]

In [15]:
movies.head(61)

                       Title  ...  Response
0   The Shawshank Redemption  ...      True
1              The Godfather  ...      True
2     The Godfather: Part II  ...      True
3            The Dark Knight  ...      True
4               12 Angry Men  ...      True
..                       ...  ...       ...
56    Grave of the Fireflies  ...      True
57            Paths of Glory  ...      True
58          Django Unchained  ...      True
59               The Shining  ...      True
60                    WALL·E  ...      True

[61 rows x 37 columns]

In [16]:
pd.set_option("display.min_rows", 2)
movies

                        Title  ...  Response
0    The Shawshank Redemption  ...      True
..                        ...  ...       ...
249                        PK  ...      True

[250 rows x 37 columns]

## Sequence of items

In [17]:
#Create "my_list" column and put a list of 100 values in each row
movies['my_list'] = [[1]*200] * 250
movies.head()

,Title,...,my_list
0,The Shawshank Redemption,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,The Godfather,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,The Godfather: Part II,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,The Dark Knight,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,12 Angry Men,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [18]:
pd.set_option("max_colwidth", None)

movies.head()

,Title,...,my_list
0,The Shawshank Redemption,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...]"
1,The Godfather,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...]"
2,The Godfather: Part II,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...]"
3,The Dark Knight,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...]"
4,12 Angry Men,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...]"

In [19]:
pd.set_option("max_seq_item", None)

movies.head()

,Title,...,my_list
0,The Shawshank Redemption,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
1,The Godfather,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
2,The Godfather: Part II,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
3,The Dark Knight,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
4,12 Angry Men,...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"

## Precision

In [20]:
#adding more decimal places to imdbRating column
movies['imdbRating'] = movies['imdbRating'] + 0.11111
movies[['imdbRating']].head()

   imdbRating
0     9.41111
1     9.31111
2     9.11111
3     9.11111
4     9.01111

In [21]:
pd.set_option('precision', 2)

movies[['imdbRating']].head()

   imdbRating
0        9.41
1        9.31
2        9.11
3        9.11
4        9.01